Import('env')

# Target specific settings
if env['BUILD_TARGET'] == 'linux':
    env['opencv_config'] = {
	'BUILD_JPEG' : True,
	'BUILD_ZLIB' : True,
	'ENABLE_SSE' : True,
    'ENABLE_SSE2' : True,
    'ENABLE_SSE3' : True,
	'WITH_FFMPEG' : True,
	'WITH_GTK' : True,
	'WITH_JPEG' : True,
	'WITH_LIBV4L' : True,
	'WITH_V4L' : True
    }
    env['OPENCVBUILDER_INCLUDE_PATHS'] = [
	'/usr/include',
	'/usr/lib',
    ]
    env['OPENCVBUILDER_LIB_PATHS'] = []

elif env['BUILD_TARGET'] == 'macosx':
    env['opencv_config'] = {
	'BUILD_JPEG' : True,
	'BUILD_ZLIB' : True,
	'ENABLE_SSE' : True,
    'ENABLE_SSE2' : True,
    'ENABLE_SSE3' : True,
	'WITH_COCOA' : True,
	'WITH_FFMPEG' : True,
	'WITH_JPEG' : True,
	'WITH_QTKIT' : True
    }
    env['OPENCVBUILDER_INCLUDE_PATHS'] = [
	'/usr/include',
	'/usr/lib',
    	# Enable macports support
	'/opt/local/include',
	'/opt/local/lib',
    ]
    env['OPENCVBUILDER_LIB_PATHS'] = [
 	'/opt/local/lib'
    ]
else:
    env['opencv_config'] = {
    }
    env['OPENCVBUILDER_INCLUDE_PATHS'] = [
	'/usr/include',
	'/usr/lib',
    ]
    env['OPENCVBUILDER_LIB_PATHS'] = []

SConscript('opencv/SConscript')
