before_install:
    - ./getOpenCv.sh

addons:
    apt:
        packages:
            - scons
            - wget

language: c++

compiler: 
    - gcc

script: 
    - scons -C example example
    - scons -C example buildAllLibsWithExample

# Require sudo for apt
sudo: required

# Hack to get a more up to date version of Ubuntu
dist: trusty
