#!/bin/sh

function logValue {
	echo "	<measurement name=\"$1\">$2</measurement>" >&$3
}

function parseAndLogValue {
	value=$(cat $1 | grep "$2" | cut -d$3 -f$4)
	logValue "$5" "$value" $6
}

function beginMeasurement {
	echo "<measurements  id=\"$1\" >" >&$2
}

function endMeasurement {
	echo "</measurements>" >&$1
}

# Check if file exists
[ ! -f $1 ] && echo "Error: file '$1' not found" && exit 1
echo "Interpreting file '$1'..."

# Check if target file is set
if [ -z $2 ]; then
	echo 'No target style set, using stdout'
	exec 3>&1
else
	exec 3> $2
fi	

# Writing xml header
echo '<?xml version="1.0" encoding="UTF-8"?>' >&3

beginMeasurement 'Total build time' 3
	parseAndLogValue $1 'Total build time' : 2 'Total-build-time' 3
endMeasurement 3

exit 0
