#!/bin/sh

function logValue {
	echo "<measurement><name>$1</name><value>$2</value></measurement>"
}

function parseAndLogValue {
	value=$(cat $1 | grep "$2" | cut -d$3 -f$4)
	logValue "$5" "$value"
}

# Check if file exists
[ ! -f $1 ] && echo "Error: file '$1' not found" && exit 1
echo "Interpreting file '$1'..."

parseAndLogValue $1 'Total build time' : 2 'Total build time'

exit 0
